- type: job
  id: Botanist
  name: job-name-botanist
  description: job-description-botanist
  playTimeTracker: JobBotanist
  startingGear: BotanistGear
  icon: "JobIconBotanist"
  supervisors: job-supervisors-hop
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 7200 #Imperial role timers
  access:
  - Service
  - Maintenance
  - Hydroponics
  extendedAccess:
  - Kitchen
  - Bar
  skills:
  - skillBotany
  - skillBaseMed
  - skillBaseConstraction
  - skillMediumBotany

- type: startingGear
  id: BotanistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitHydroponics
    back: ClothingBackpackHydroponicsFilled
    shoes: ClothingShoesColorBrown
    id: BotanistPDA
    ears: ClothingHeadsetService
    outerClothing: ClothingOuterApronBotanist
    belt: ClothingBeltPlantFilled
  innerClothingSkirt: ClothingUniformJumpskirtHydroponics
  satchel: ClothingBackpackSatchelHydroponicsFilled
  duffelbag: ClothingBackpackDuffelHydroponicsFilled
